
# deploy.yml

name: Deploy to Slack Cloud

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v3

      - name: Install CLI
        run: curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash

      - name: Deploy
        run: slack deploy --app ${{ secrets.APP }} --team ${{ secrets.TEAM }} --token ${{ secrets.SLACK_SERVICE_TOKEN }}