
# deploy.yml

name: Deploy to Slack Cloud

on:
  workflow_run:
    workflows: ["Deno app build and testing"]
    types:
      - completed

jobs:
  deploy:
    # Only run the deployment when merging to main AND tests have run successfully
    if: ${{ github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v3

      - name: Install CLI
        run: curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash

      - name: Deploy
        run: slack deploy --app ${{ secrets.APP }} --team ${{ secrets.TEAM }} --token ${{ secrets.SLACK_SERVICE_TOKEN }}